#!/usr/bin/env python3
"""gen_session_tape.py — script.json -> a VHS tape that films a real Claude Code
TUI with DETERMINISTIC voice-leads-typing slots, plus a plan.json the overlay
step uses to place the narration.

Design: docs/plans/2026-06-27-claude-session-voiceover-sync-design.md.
Per turn the timeline has controllable SOFT slots (pre-prompt pause, typing,
post-output hold) around the non-controllable HARD axis (claude's think gap,
Enter->sentinel). We synthesize the intro/outro voice up front, measure each,
and size the SOFT Sleeps to fit them — so the intro voice provably ENDS before
typing starts (voice-leads-typing) and the outro fits the post-output hold. The
think voice rides the real gap and is fitted later (session_overlay.py).

Inputs : script.json  (see script.example.json) — one {prompt,intro,think,outro}
         per turn.
Outputs: <out>.tape, <demo>/plan.json, <demo>/_voice/{intro,think,outro}_<i>.mp3
         (voice clips are pre-synthesized so build is reproducible).

Prereq : run claude_sandbox.sh <demo> first; render the tape from <demo>/.
Example:
  ./claude_sandbox.sh /tmp/sess
  python3 gen_session_tape.py --demo /tmp/sess --script script.example.json \
      -o /tmp/sess/session.tape
  cd /tmp/sess && vhs session.tape           # -> terminal.mp4 + session-timeline.jsonl
  python3 session_overlay.py --demo /tmp/sess # -> session.mp4 + .srt
"""
import argparse
import json
import os
import subprocess

THEMES = {"dark": "Catppuccin Mocha", "light": "Catppuccin Latte"}
VOICE = "zh-TW-HsiaoChenNeural"
RATE = "+0%"
# soft-slot padding (seconds): silence kept around each voice clip so it never
# butts hard against the next action. INTRO_LEAD = beat after intro before typing.
INTRO_LEAD = 0.6
PRE_ENTER = 0.4          # beat after typing finishes, before Enter
HOLD = 1.0              # silence after outro before quitting / next turn
OPEN_LEAD = 0.6         # the open voice leads the launch-command typing by this much
CLOSE_HOLD = 1.0        # silence after the close narration before quitting
PRELUDE = 2.0           # Sleep before the launch typing (shell prompt settles)
BEAT_GAP = 0.6          # silence between consecutive launch-flag narrations


def synth(text, out_mp3):
    """edge-tts -> mp3, return its duration in seconds."""
    subprocess.run(["edge-tts", "--voice", VOICE, "--rate", RATE,
                    "--text", text, "--write-media", out_mp3],
                   check=True, capture_output=True)
    dur = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", out_mp3],
        check=True, capture_output=True, text=True).stdout.strip()
    return round(float(dur), 3)


def emit(spec, demo, voice_dir, theme, font_size, width, height,
         word_delay, startup_to, turn_to, tape_path, video):
    turns = spec["turns"]
    cfg = os.path.join(os.path.abspath(demo), ".cfg")
    os.makedirs(voice_dir, exist_ok=True)
    L, plan = [], {"word_delay_ms": word_delay, "intro_lead": INTRO_LEAD,
                   "pre_enter": PRE_ENTER, "hold": HOLD, "prelude": PRELUDE,
                   "open_lead": OPEN_LEAD, "close_hold": CLOSE_HOLD, "turns": []}
    a = L.append
    a("# Auto-generated by gen_session_tape.py — films a real Claude Code TUI with")
    a("# deterministic voice-leads-typing slots. Prereq: claude_sandbox.sh <demo>.")
    a(f"Output {video}")
    a("")
    a(f"Set FontSize {font_size}")
    a(f"Set Width {width}")
    a(f"Set Height {height}")
    a(f'Set Theme "{theme}"')
    a("Set TypingSpeed 0ms        # word-by-word reveal via explicit Sleeps")
    a("")
    a('Env VHS_DEMO "1"')
    a(f'Env CLAUDE_CONFIG_DIR "{cfg}"')
    a("")
    a(f"Sleep {PRELUDE:.0f}s                   # let the shell prompt settle")
    # LAUNCH as a CLI lesson (sync-model v5 hero-command pacing): type `claude`,
    # then each flag, HOLDING on each token while its narration plays — so the
    # flag is on screen exactly while we explain it. The pause after a token = the
    # duration of that token's narration. What's narrated == typed == executed.
    lc = spec.get("launch", {"base": "claude", "flags": [], "intro": "", "outro": ""})
    # beats: (token_to_type, narration). base carries the intro; each flag its
    # own say. Each beat is a SEPARATE clip (not one dense combined clip — that
    # reads sentences back-to-back and sounds rushed); placed with BEAT_GAP of
    # breathing room. The outro is its own clip played during boot.
    beats = [(lc.get("base", "claude"), lc.get("intro", ""))]
    for f in lc.get("flags", []):
        beats.append((f["arg"], f.get("say", "")))
    # VOICE-LEADS each flag: narrate it FIRST, then the token is typed (it appears
    # the instant the narration ends — typing is instant, so the text must not show
    # until we've explained it). Same rule for every command/flag, claude or not.
    beat_meta, tokens = [], []
    for ti, (tok, say) in enumerate(beats):
        tokens.append(tok)
        mp3 = os.path.join(voice_dir, f"open_beat{ti}.mp3")
        d = synth(say, mp3) if say else 0.0
        a(f"Sleep {d:.3f}s   # narrate `{tok}` ({d:.2f}s) — token not shown yet")
        a(f'Type "{tok}"' if ti == 0 else f'Type " {tok}"')   # appears AFTER narration
        a(f"Sleep {BEAT_GAP:.3f}s   # breath before the next flag")
        beat_meta.append({"text": say, "token": tok,
                          "mp3": os.path.relpath(mp3, demo) if d else "", "dur": d})
    a("Enter")
    a(f"Wait+Screen@{startup_to}s /shift\\+tab|for shortcuts/")
    a("")
    outro_mp3 = os.path.join(voice_dir, "open_outro.mp3")
    outro_dur = synth(lc["outro"], outro_mp3) if lc.get("outro") else 0.0
    plan["open"] = {"command": " ".join(tokens), "open_lead": OPEN_LEAD,
                    "beat_gap": BEAT_GAP, "beats": beat_meta,
                    "outro": {"text": lc.get("outro", ""),
                              "mp3": os.path.relpath(outro_mp3, demo) if outro_dur else "",
                              "dur": outro_dur}}
    for i, t in enumerate(turns, 1):
        # pre-synthesize the deterministic (intro/outro) AND the gap (think) voice
        intro_mp3 = os.path.join(voice_dir, f"intro_{i}.mp3")
        think_mp3 = os.path.join(voice_dir, f"think_{i}.mp3")
        outro_mp3 = os.path.join(voice_dir, f"outro_{i}.mp3")
        intro_dur = synth(t["intro"], intro_mp3) if t.get("intro") else 0.0
        think_dur = synth(t["think"], think_mp3) if t.get("think") else 0.0
        outro_dur = synth(t["outro"], outro_mp3) if t.get("outro") else 0.0
        words = t["prompt"].split(" ")
        type_dur = round(len(words) * word_delay / 1000.0, 3)

        a(f"# --- Turn {i} ---")
        a(f"Sleep {intro_dur + INTRO_LEAD:.3f}s   # ① intro slot: voice leads (intro {intro_dur:.2f}s + lead)")
        for w, word in enumerate(words):
            a(f'Type "{word}"' if w == 0 else f'Type " {word}"')
            a(f"Sleep {word_delay}ms")
        a(f"Sleep {PRE_ENTER:.3f}s          # ② beat before Enter")
        a("Enter")
        a(f"Wait+Screen@{turn_to}s /VHS_TURN_DONE_{i}/   # ③ HARD axis: real think gap")
        a(f"Sleep {outro_dur + HOLD:.3f}s   # ④ outro slot: voice fits hold (outro {outro_dur:.2f}s + hold)")
        a("")
        plan["turns"].append({
            "index": i, "prompt": t["prompt"], "sentinel": f"VHS_TURN_DONE_{i}",
            "intro": {"text": t.get("intro", ""), "mp3": os.path.relpath(intro_mp3, demo), "dur": intro_dur},
            "think": {"text": t.get("think", ""), "mp3": os.path.relpath(think_mp3, demo), "dur": think_dur},
            "outro": {"text": t.get("outro", ""), "mp3": os.path.relpath(outro_mp3, demo), "dur": outro_dur},
            "type_dur": type_dur,
        })
    # close slot: wrap-up narration before quitting (SessionEnd region)
    close_dur = synth(spec["close"], os.path.join(voice_dir, "close.mp3")) if spec.get("close") else 0.0
    if close_dur:
        a(f"Sleep {close_dur + CLOSE_HOLD:.3f}s   # CLOSE slot: wrap-up narration (close {close_dur:.2f}s + hold)")
    plan["close"] = {"text": spec.get("close", ""),
                     "mp3": os.path.relpath(os.path.join(voice_dir, "close.mp3"), demo) if close_dur else "",
                     "dur": close_dur}
    a("Sleep 500ms")
    a("Ctrl+C")
    a("Sleep 500ms")
    a("Ctrl+C")
    a("Sleep 1s")
    open(tape_path, "w").write("\n".join(L) + "\n")
    json.dump(plan, open(os.path.join(demo, "plan.json"), "w"),
              ensure_ascii=False, indent=2)
    print(f"wrote {tape_path}  ({len(turns)} turns)")
    print(f"wrote {os.path.join(demo, 'plan.json')}  + voice clips in {voice_dir}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--demo", required=True, help="sandbox dir (from claude_sandbox.sh)")
    ap.add_argument("--script", required=True, help="script.json (prompt+intro/think/outro per turn)")
    ap.add_argument("-o", "--output", default=None, help="tape path (default <demo>/session.tape)")
    ap.add_argument("--video", default="terminal.mp4", help="VHS Output target")
    ap.add_argument("--theme", choices=THEMES, default="dark")
    ap.add_argument("--font-size", type=int, default=27)
    ap.add_argument("--width", type=int, default=1600)
    ap.add_argument("--height", type=int, default=900)
    ap.add_argument("--word-delay", type=int, default=220, help="ms between prompt words")
    ap.add_argument("--startup-timeout", type=int, default=60)
    ap.add_argument("--turn-timeout", type=int, default=120)
    args = ap.parse_args()
    spec = json.load(open(args.script, encoding="utf-8"))
    tape_path = args.output or os.path.join(args.demo, "session.tape")
    voice_dir = os.path.join(args.demo, "_voice")
    emit(spec, args.demo, voice_dir, THEMES[args.theme], args.font_size,
         args.width, args.height, args.word_delay, args.startup_timeout,
         args.turn_timeout, tape_path, args.video)


if __name__ == "__main__":
    main()
