#!/usr/bin/env python3
"""gen_session_tape.py — prompts -> a VHS tape that films a REAL Claude Code TUI.

Implements the Roadmap "session tape": launch `claude` inside the isolated
sandbox (claude_sandbox.sh), drive each prompt word-by-word, and wait on the
on-screen VHS_TURN_DONE_N sentinel between turns — never a guessed Sleep, because
claude's response time is non-deterministic.

The tape sets two env vars VHS injects into its headless shell:
  VHS_DEMO=1                      -> arms vhs_stop_sentinel.sh
  CLAUDE_CONFIG_DIR=<demo>/.cfg   -> the clean, isolated user config
and launches with --dangerously-skip-permissions so a turn that runs a shell
command (e.g. running the test it just wrote) doesn't hang on a permission
prompt (acceptEdits is NOT enough — it auto-accepts edits but not Bash).

Run claude_sandbox.sh on the demo dir FIRST; then render the emitted tape from
that dir so terminal.mp4 lands beside it.

Example:
  ./claude_sandbox.sh /tmp/sess && \
  python3 gen_session_tape.py --demo /tmp/sess -o /tmp/sess/session.tape \
    "write a Python function fizzbuzz(n) that prints FizzBuzz from 1 to n" \
    "now add a docstring and a simple test" && \
  cd /tmp/sess && vhs session.tape           # -> terminal.mp4
"""
import argparse
import os

THEMES = {"dark": "Catppuccin Mocha", "light": "Catppuccin Latte"}


def emit(prompts, demo, theme, font_size, width, height,
         word_delay, read_pause, startup_to, turn_to, output, video):
    cfg = os.path.join(os.path.abspath(demo), ".cfg")
    L = []
    a = L.append
    a("# Auto-generated by gen_session_tape.py — films a real Claude Code TUI.")
    a("# Prereq: run claude_sandbox.sh <demo> first. Render from <demo>/.")
    a(f"Output {video}")
    a("")
    a(f"Set FontSize {font_size}")
    a(f"Set Width {width}")
    a(f"Set Height {height}")
    a(f'Set Theme "{theme}"')
    a("Set TypingSpeed 0ms        # word-by-word reveal via explicit Sleeps")
    a("")
    a('Env VHS_DEMO "1"')
    a(f'Env CLAUDE_CONFIG_DIR "{cfg}"')
    a("")
    a("Sleep 2s                   # let the shell prompt settle")
    a('Type "claude --dangerously-skip-permissions"')
    a("Enter")
    a(f"Wait+Screen@{startup_to}s /shift\\+tab|for shortcuts/")
    a("")
    for i, p in enumerate(prompts, 1):
        a(f"# --- Turn {i} ---")
        for w, word in enumerate(p.split(" ")):
            a(f'Type "{word}"' if w == 0 else f'Type " {word}"')
            a(f"Sleep {word_delay}ms")
        a(f"Sleep {read_pause}s          # read-pause before sending")
        a("Enter")
        a(f"Wait+Screen@{turn_to}s /VHS_TURN_DONE_{i}/")
        a("")
    a("Sleep 5s                   # hold on the finished response")
    a("Ctrl+C")
    a("Sleep 500ms")
    a("Ctrl+C")
    a("Sleep 1s")
    open(output, "w").write("\n".join(L) + "\n")
    print(f"wrote {output}  ({len(prompts)} turns)")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("prompts", nargs="+", help="one quoted string per turn")
    ap.add_argument("--demo", required=True, help="sandbox dir (from claude_sandbox.sh)")
    ap.add_argument("-o", "--output", default="session.tape", help="tape file to write")
    ap.add_argument("--video", default="terminal.mp4",
                    help="VHS Output target (the filmed mp4 overlay.py consumes)")
    ap.add_argument("--theme", choices=THEMES, default="dark")
    ap.add_argument("--font-size", type=int, default=27)
    ap.add_argument("--width", type=int, default=1600)
    ap.add_argument("--height", type=int, default=900)
    ap.add_argument("--word-delay", type=int, default=220, help="ms between words")
    ap.add_argument("--read-pause", type=int, default=3, help="s before Enter")
    ap.add_argument("--startup-timeout", type=int, default=60)
    ap.add_argument("--turn-timeout", type=int, default=120)
    args = ap.parse_args()
    emit(args.prompts, args.demo, THEMES[args.theme], args.font_size,
         args.width, args.height, args.word_delay, args.read_pause,
         args.startup_timeout, args.turn_timeout, args.output, args.video)


if __name__ == "__main__":
    main()
