#!/usr/bin/env python3
"""gen_capture_tape.py — script.json -> a MINIMAL VHS tape that films a real
Claude Code TUI for the v6 deterministic pipeline (Phase 0: capture).

The v6 change vs v5's gen_session_tape.py: there is NO voice here. v5
synthesized intro/think/outro up front and SIZED the soft Sleeps to fit each
clip (voice-leads-typing). v6 instead captures with FIXED tiny pads and
re-times everything later by splicing freeze-frames against the synthesized
narration. So this tape has NO edge-tts, NO voice clips, NO voice-sized Sleeps
— only the fixed PAD/PRE_ENTER/PRELUDE constants.

It films `terminal_raw.mp4` and writes a `capture.json` describing the structure
detect_anchors needs: n turns, per-turn `type_dur`, prompts, launch token list.

Inputs : script.json (see script.example.json) — only `launch.base`,
         `launch.flags[].arg`, and `turns[].prompt` are read here; the voice
         fields (intro/think/outro/say/note/close) are ignored at this stage.
Outputs: <demo>/session.tape + <demo>/capture.json

Prereq : run claude_sandbox.sh <demo> first; render the tape from <demo>/.
Example:
  ./claude_sandbox.sh /tmp/sess
  python3 gen_capture_tape.py --demo /tmp/sess --script script.example.json
  cd /tmp/sess && vhs session.tape   # -> terminal_raw.mp4 + session-timeline.jsonl
"""
import argparse
import json
import os

THEMES = {"dark": "Catppuccin Mocha", "light": "Catppuccin Latte"}
PAD = 0.4          # fixed tiny soft pad around each action (no voice sizing)
PRELUDE = 2.0      # Sleep before the launch typing (shell prompt settles)
PRE_ENTER = 0.4    # beat after typing finishes, before Enter


def render(spec, demo, width, height, font_size, word_delay,
           startup_to=60, turn_to=120, theme="Catppuccin Mocha"):
    """Pure: build (tape_str, plan) from spec. Writes NOTHING to disk."""
    turns = spec["turns"]
    cfg = os.path.join(os.path.abspath(demo), ".cfg")
    timeline = os.path.join(os.path.abspath(demo), "session-timeline.jsonl")

    lc = spec.get("launch", {"base": "claude", "flags": []})
    base = lc.get("base", "claude")
    flags = lc.get("flags", [])
    tokens = [base] + [f["arg"] for f in flags]

    L = []
    a = L.append
    a("# Auto-generated by gen_capture_tape.py — minimal prompts-only capture tape")
    a("# (no voice, fixed pads). Prereq: claude_sandbox.sh <demo>.")
    a("Output terminal_raw.mp4")
    a("")
    a(f"Set FontSize {font_size}")
    a(f"Set Width {width}")
    a(f"Set Height {height}")
    a(f'Set Theme "{theme}"')
    a("Set TypingSpeed 0ms        # word-by-word reveal via explicit Sleeps")
    a("")
    a('Env VHS_DEMO "1"')
    a(f'Env CLAUDE_CONFIG_DIR "{cfg}"')
    a(f'Env VHS_TIMELINE "{timeline}"')
    # Clean SHELL PROMPT. The killer: VHS defaults to bash, which inherits the
    # EXPORTED zsh-syntax `PS1` from the p10k shell this runs in and renders it as
    # literal `${_p9k_…}` garbage full-screen at boot AND on Ctrl+C exit — both
    # uglifying the opening/closing frames and reading as two extra full-bright
    # "prompt submissions" that break detect_turns (4 detected vs 2). Overriding
    # PS1/PROMPT in the tape kills the dump regardless of which shell VHS picks.
    # ZDOTDIR (clean .zshrc) is kept as defense-in-depth for the zsh path.
    a('Env PS1 "❯ "')
    a('Env PROMPT "❯ "')
    a(f'Env ZDOTDIR "{os.path.join(cfg, "zdotdir")}"')
    a("")
    a(f"Sleep {PRELUDE:.0f}s                   # let the shell prompt settle")
    # LAUNCH typed token-by-token: `claude`, then each flag (leading space),
    # with a fixed PAD between tokens. No narration.
    for ti, tok in enumerate(tokens):
        a(f'Type "{tok}"' if ti == 0 else f'Type " {tok}"')
        a(f"Sleep {PAD:.3f}s   # fixed pad after token")
    a("Enter")
    a(f"Wait+Screen@{startup_to}s /shift\\+tab|for shortcuts/")
    a("")

    plan = {
        "launch": {"tokens": tokens, "base": base, "flags": flags},
        "pre_enter": PRE_ENTER, "prelude": PRELUDE, "pad": PAD,
        "turns": [],
    }
    for i, t in enumerate(turns, 1):
        words = t["prompt"].split(" ")
        type_dur = round(len(words) * word_delay / 1000.0, 3)
        a(f"# --- Turn {i} ---")
        a(f"Sleep {PAD:.3f}s   # pre-prompt pad")
        for w, word in enumerate(words):
            a(f'Type "{word}"' if w == 0 else f'Type " {word}"')
            a(f"Sleep {word_delay}ms")
        a(f"Sleep {PRE_ENTER:.3f}s          # beat before Enter")
        a("Enter")
        a(f"Wait+Screen@{turn_to}s /VHS_TURN_DONE_{i}/   # HARD axis: real think gap")
        a(f"Sleep {PAD:.3f}s   # settle pad")
        a("")
        plan["turns"].append({
            "index": i, "prompt": t["prompt"], "sentinel": f"VHS_TURN_DONE_{i}",
            "type_dur": type_dur,
        })
    # teardown
    a("Sleep 500ms")
    a("Ctrl+C")
    a("Sleep 500ms")
    a("Ctrl+C")
    a("Sleep 1s")
    return "\n".join(L) + "\n", plan


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--demo", required=True, help="sandbox dir (from claude_sandbox.sh)")
    ap.add_argument("--script", required=True, help="script.json (prompt per turn)")
    ap.add_argument("-o", "--output", default=None, help="tape path (default <demo>/session.tape)")
    ap.add_argument("--theme", choices=THEMES, default="dark")
    ap.add_argument("--font-size", type=int, default=27)
    ap.add_argument("--width", type=int, default=1600)
    ap.add_argument("--height", type=int, default=900)
    ap.add_argument("--word-delay", type=int, default=220, help="ms between prompt words")
    ap.add_argument("--startup-timeout", type=int, default=60)
    ap.add_argument("--turn-timeout", type=int, default=120)
    args = ap.parse_args()
    spec = json.load(open(args.script, encoding="utf-8"))
    tape_path = args.output or os.path.join(args.demo, "session.tape")
    tape, plan = render(spec, args.demo, args.width, args.height, args.font_size,
                        args.word_delay, args.startup_timeout, args.turn_timeout,
                        THEMES[args.theme])
    open(tape_path, "w").write(tape)
    json.dump(plan, open(os.path.join(args.demo, "capture.json"), "w"),
              ensure_ascii=False, indent=2)
    print(f"wrote {tape_path}  ({len(spec['turns'])} turns)")
    print(f"wrote {os.path.join(args.demo, 'capture.json')}")


if __name__ == "__main__":
    main()
