#!/usr/bin/env python3
"""Build a CLI lesson: ONE continuous narration + an explainshell side panel.

Tool-agnostic engine. The CONTENT (narration, commands, panel tokens) comes
from the active lesson (lessons/<name>/lesson.py, picked by config.toml); this
file knows nothing about rsync or any specific tool.

The voice never stops — it flows sentence to sentence. On-screen actions are
pinned to sentence timestamps inside that single audio (edge-tts gives a real
time for every sentence end). The HERO command of each scene is typed token by
token at a deliberate pace, and each token's panel annotation reveals the moment
that token finishes typing — so the explanatory sentence walks the flags in the
same order they appear. overlay.py paints the panel. Subtitles ship as a sidecar
.srt (not burned in)."""
import json
import os
import subprocess
import tomllib

import lesson                                  # S/R/CLR builders + lesson loader

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # clip/
LESSONS_DIR = f"{ROOT}/lessons"
CFG = tomllib.load(open(f"{ROOT}/config.toml", "rb"))
VOICE, RATE = CFG["voice"]["name"], CFG["voice"]["rate"]
_T, _R = CFG["timing"], CFG["render"]

TS = _T["ts"]       # MODELLED real per-char typing (calibrated; ≠ Set TypingSpeed)
ENTER = 0.0
INITIAL = _T["initial"]
OUTPUT_MIN = _T["output_min"]
TAIL = _T["tail"]

# Content comes from the active lesson. Precedence: $LESSON env (used by the
# /clip workflow to target one slug without touching config) > config.toml
# [lesson] active > "rsync". The lesson supplies SCRIPT plus a SLUG/TITLE that
# name the outputs.
ACTIVE = lesson.active_slug(ROOT)
_L = lesson.load(ACTIVE, LESSONS_DIR)
SCRIPT, SLUG, TITLE = _L.SCRIPT, _L.SLUG, _L.TITLE
# per-slug workspace so concurrent renders don't collide (see lesson.workspace)
DEMO = lesson.workspace(ROOT, SLUG)
AUDIO = f"{DEMO}/audio"


def parse_srt(path):
    def t2s(t):
        h, m, r = t.split(":")
        s, ms = r.split(",")
        return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000
    cues, block = [], []
    for line in open(path, encoding="utf-8").read().splitlines() + [""]:
        if line.strip() == "":
            if len(block) >= 3:
                a, b = block[1].split(" --> ")
                cues.append([t2s(a), t2s(b), " ".join(block[2:]).strip()])
            block = []
        else:
            block.append(line)
    return cues


def main():
    says = [i[1] for i in SCRIPT if i[0] == "say"]
    text = "".join(says)
    os.makedirs(AUDIO, exist_ok=True)
    # namespace the narration cache by lesson so switching lessons never reuses
    # another lesson's voice track
    mp3, srt = f"{AUDIO}/{SLUG}.mp3", f"{AUDIO}/{SLUG}.srt"
    if not (os.path.exists(mp3) and os.path.exists(srt)):
        subprocess.run(["edge-tts", "--voice", VOICE, "--rate", RATE,
                        "--text", text, "--write-media", mp3,
                        "--write-subtitles", srt], check=True)
    D = float(subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", mp3], capture_output=True, text=True).stdout)
    cues = parse_srt(srt)
    if len(cues) != len(says):
        print(f"WARNING cue/sentence mismatch: {len(cues)} vs {len(says)}")
        for i, c in enumerate(cues):
            print(f"  cue{i}: {c[2]}")
        return

    tape = [
        f"# Auto-generated by build.py for lesson '{SLUG}' — narration + panel.",
        "Output terminal.mp4",
        "Set Shell zsh",
        f"Set FontSize {_R['font_size']}", f"Set Width {_R['width']}",
        f"Set Height {_R['height']}",
        'Set Theme "Catppuccin Mocha"',
        # keep Set at 45ms (the config measured to yield ~24ms/char real); TS
        # models that real rate, so don't derive this from TS.
        f"Set TypingSpeed {_R['typing_speed_ms']}ms", "Set Padding 28", "",
        # enable `#` comments AND clear, all hidden, so t=0 opens on a clean
        # prompt (no leftover `setopt ...` line visible at the start).
        "Hide", 'Type "setopt interactive_comments"', "Enter",
        'Type "clear"', "Enter", "Sleep 200ms", "Show", "",
    ]
    vt = 0.0

    def sleep_to(target):
        nonlocal vt
        dt = target - vt
        if dt > 0.02:
            tape.append(f"Sleep {round(dt, 2)}s")
            vt = target

    sleep_to(INITIAL)
    si = -1
    panels, cur, cur_toks = [], None, []

    def finalize(end):
        if cur:
            cur["show_to"] = round(end, 3)
            panels.append(cur)

    for item in SCRIPT:
        kind = item[0]
        if kind == "say":
            si += 1
        elif kind == "clear":
            b = cues[si][1] if si >= 0 else 0.0
            sleep_to(INITIAL + b)
            tape += ["Hide", 'Type "clear"', "Enter", "Sleep 120ms", "Show"]
            finalize(INITIAL + b)
            _, key, hero, toks = item
            cur = (dict(banner=round(INITIAL + b, 3), key=key, hero=hero,
                        cmd=None, cmd_start=None, tokens=[]) if key else None)
            cur_toks = toks
        elif kind == "run":
            cmd = item[1]
            cs, ce = cues[si][0], cues[si][1]
            sleep_to(INITIAL + cs)
            is_hero = cur is not None and cur["hero"] == cmd and cur_toks
            if is_hero:
                pos, spec = 0, []
                for sub, ann, role in cur_toks:
                    idx = cmd.find(sub, pos); end = idx + len(sub); pos = end
                    spec.append((idx, end, sub, ann, role))
                # Type each token so it lands *when the voice names that flag* —
                # spread across the explain sentence, not clustered at the start.
                # Find where the flag is spoken (its char position in the
                # sentence) and map that to a time inside the cue.
                text = cues[si][2]; L = max(1, len(text)); dur = ce - cs
                n = len(spec)

                def vfrac(sub, role, i):
                    for key in (sub, sub.lstrip("-"), sub.split("=")[0].lstrip("-")):
                        if key and key in text:
                            return text.index(key) / L
                    if role == "path" and "A" in text:
                        return text.index("A") / L
                    return (i + 1) / (n + 1)            # even-spread fallback

                vrel, prevv = [], 0.0
                for i, (idx, end, sub, ann, role) in enumerate(spec):
                    v = max(prevv + 0.4, vfrac(sub, role, i) * dur)
                    v = min(v, dur - 0.2)               # leave a beat before <CR>
                    vrel.append(v); prevv = v
                prefix = cmd[:spec[0][0]]
                tape.append(f'Type "{prefix}"')
                vt += len(prefix) * TS
                prev = spec[0][0]
                cur["cmd"] = cmd
                cur["cmd_start"] = round(INITIAL + cs, 3)
                for (idx, end, sub, ann, role), v in zip(spec, vrel):
                    chunk = cmd[prev:end]
                    sleep_to(INITIAL + cs + v - len(chunk) * TS)  # land at voice
                    tape.append(f'Type "{chunk}"')
                    vt += len(chunk) * TS
                    prev = end
                    cur["tokens"].append(dict(label=sub, ann=ann, role=role,
                                              cs=idx, ce=end, reveal=round(vt, 3)))
                if cmd[prev:]:
                    tape.append(f'Type "{cmd[prev:]}"')
                    vt += len(cmd[prev:]) * TS
            else:
                tape.append(f'Type "{cmd}"')
                vt += len(cmd) * TS
            sleep_to(INITIAL + ce)               # hold until the sentence ends
            tape.append("Enter")
            vt += ENTER
            sleep_to(vt + OUTPUT_MIN)
    sleep_to(INITIAL + D)
    tape += [f"Sleep {TAIL}s", ""]
    total = vt + TAIL
    finalize(total)

    open(f"{DEMO}/demo.tape", "w").write("\n".join(tape))
    json.dump(dict(slug=SLUG, title=TITLE,
                   predicted_total=round(total, 3), anchor=INITIAL, mp3=mp3,
                   narration_dur=round(D, 3),
                   cues=[[round(a, 3), round(b, 3), x] for a, b, x in cues],
                   panels=panels),
              open(f"{DEMO}/timeline.json", "w"), ensure_ascii=False, indent=2)
    print(f"[{SLUG}] predicted total = {total:.1f}s, narration = {D:.1f}s, "
          f"{len(cues)} sentences, {len(panels)} panels")


if __name__ == "__main__":
    main()
